description: Describe how the game should work

update_interval:
  description: ms between dynamic obstacle moves or movement
  required: false
  default: 500
  type: int
color_agent:
  description: Color for current position.
  required: false
  default: [0, 0, 255]
  value_range: [0, 255]
  length_range: [3,3]
  type: list(int)
color_goal:
  description: Color for the goal position.
  required: false
  default: [255, 0, 0]
  value_range: [0, 255]
  length_range: [3,3]
  type: list(int)
color_start:
  description: Color for the goal position.
  required: false
  default: [0, 255, 0]
  value_range: [0, 255]
  length_range: [3,3]
  type: list(int)
