description: Describe how the game should work
update_interval:
  description: ms between dynamic obstacle moves or movement
  required: false
  default: 500
  type: int
fps:
  description: Desired frames per second for the game loop
  required: false
  default: 30
  type: int
seed:
  description: Seed to use for the game
  required: false
  default: None
  type: int
agent_types:
  description: List of agents to run and tests
  required: false
  default: ["dstar", "astar"]
  type: list(str)
maps_to_test:
  description: Number of map to test
  required: false
  default: 10
  type: int
spawns_per_map:
  description: Number of time each agent will spawn for every map.
  required: false
  default: 2
  type: int
