description: Describe the scene use by the game

grid_width:
  description: number of cells horizontally
  required: false
  default: 50
  type: int
grid_height:
  description: number of cells vertically
  required: false
  default: 40
  type: int
cell_size:
  description: pixel size of each cell
  required: false
  default: 10
  type: int
num_static_areas:
  description: number of static (non-moving) obstacle groups
  required: false
  default: 20
  type: int
num_dynamic_areas:
  description: number of moving obstacle groups
  required: false
  default: 5
  type: int

