description: Describe the scene use by the game

grid_width:
  description: number of cells horizontally
  required: false
  default: 50
  type: int
grid_height:
  description: number of cells vertically
  required: false
  default: 40
  type: int
erosion_size:
  description: number of cells that are padded around abjects
  required: false
  default: 1
  type: int
cell_size:
  description: pixel size of each cell
  required: false
  default: 10
  type: int
num_static_areas:
  description: number of static (non-moving) obstacle groups
  required: false
  default: 20
  type: int
num_dynamic_areas:
  description: number of moving obstacle groups
  required: false
  default: 5
  type: int
color_obstacle:
  description: Color for the obstacles.
  required: false
  default: [0, 0, 0]
  value_range: [0, 255]
  length_range: [3,3]
  type: list(int)
color_grid_line:
  description: Color for the grid lines separating the tiles.
  required: false
  default: [200, 200, 200]
  value_range: [0, 255]
  length_range: [3,3]
  type: list(int)
color_erosion:
  description: Color for the eroded cells around abstacles.
  required: false
  default: [255, 155, 155]
  value_range: [0, 255]
  length_range: [3,3]
  type: list(int)
