experiment_name:
  description: Name to use to reference this experiment
  required: true
  type: str
output_folder:
  description: Output folder used to output traces
  required: false
  default: output
  type: str
fps:
  description: Desired frames per second for the game loop
  required: false
  default: 30
  type: int
seed:
  description: Seed to use for the game
  required: false
  default: None
  type: int | None
runtime_type:
  description: The way we want to manage the gameplay
  required: true
  values: [Generate, Replay]
  type: enum

display_debug_values:
  description: The values that we want to display in the debug window.
  required: False
  default: []
  type: list(str)

agent_types:
  description: List of agents to run and tests
  required: false
  default: ["dstar", "astar", "replay", "dijkstra", "monte_carlo"]
  type: list(str)
maps_to_test:
  description: Number of map to test
  required: false
  default: 10
  type: int
spawns_per_map:
  description: Number of time each agent will spawn for every map.
  required: false
  default: 2
  type: int
replay_folder:
  description: The folder to use to load replays
  required: false
  default: None
  type: str | None
record_trace:
  description: Set to true if you want to record the traces.
  required: false
  default: True
  type: bool

game:
  $ref: ./game.yaml
  required: false
map:
  $ref: ./map.yaml
  required: false

color_background:
  description: Color for the background.
  required: false
  default: [255, 255, 255]
  value_range: [0, 255]
  length_range: [3,3]
  type: list(int)