experiment_name:
  description: Name to use to reference this experiment
  required: true
  type: str

game:
  $ref: ./game.yaml
  required: false
map:
  $ref: ./map.yaml
  required: false

color_background:
  description: Color for the background.
  required: false
  default: [255, 255, 255]
  value_range: [0, 255]
  length_range: [3,3]
  type: list(int)