experiment_name:
  description: Name to use to reference this experiment
  required: true
  type: str

map_id:
  description: Desired map to consider when parsing traces
  required: false
  default: 0
  type: str

agent_type:
  description: Desired agent type to consider when parsing traces
  required: false
  default: a_star
  type: str