experiment_name: default_config
seed: 42
runtime_type: Generate
display_debug_values: [start_pos, goal_pos]

agent_types: [astar, dstar]
maps_to_test: 1
spawns_per_map: 5

agent_export_fields: [agent_type, spawn_index, map_index, start_pos, goal_pos, agent_visited]

map:
  num_dynamic_areas: 0

game:
  update_interval: 20