experiment_name: default_config
seed: 42
runtime_type: Generate
display_debug_values: [start_pos, goal_pos]

agent_types: [astar, dstar, dijkstra]
maps_to_test: 2
spawns_per_map: 2

map:
  num_dynamic_areas: 0